# 端口号
server:
  port: 8089

# dubbo配置，参考：https://dubbo.apache.org/zh/docs/v2.7/user/references/
dubbo:
  application:
    name: dubbo-consumer
  protocol:
    port: 20881
    name: dubbo
  scan:
    base-packages: com.dm.service
  # 注册中心配置
  registry:
    # 单机配置方法1：
    # address: zookeeper://127.0.0.1:2181
    # 单机配置方法2：
    protocol: zookeeper
    address: 127.0.0.1:2181
    # 集群配置方法1：
    # address: zookeeper://192.168.186.130:2181?backup=192.168.186.131:2181,192.168.186.132:2181
    # 集群配置方法2(未验证)：
    # protocol: zookeeper
    # address: 127.0.0.1:2181，127.0.0.1:2182，127.0.0.1:2183
    # 超时时间
    timeout: 10000
  # 消费者配置
  consumer:
    # 关闭所有服务的启动时检查：（没有提供者时，启动报错）
    check: false
    # 超时时间
    timeout: 10000
  # 提供者配置
  provider:
    # 超时时间
    timeout: 10000

